// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:c385325b-ba3d-4f0b-b17d-ced3b8d37dfc",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_1rrX8nVRK",
    "aws_user_pools_web_client_id": "164faki76hbeqf3vji0vjrphdr",
    "oauth": {}
};

export default awsmobile;