// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-central-1",
    "aws_cognito_identity_pool_id": "eu-central-1:ae210395-8450-47cf-a6b0-e9db180eb013",
    "aws_cognito_region": "eu-central-1",
    "aws_user_pools_id": "eu-central-1_Bo6dnKvLw",
    "aws_user_pools_web_client_id": "7ed96iv3rd93bttdkeqjh9vaik",
    "oauth": {}
};


export default awsmobile;
